---
- name: set up http server
  hosts: localhost
  tasks:
      - name: install httpd package
        yum:
          name: "httpd"
          state: "latest"

      - name: set up simple home page
        copy:
          dest: "/var/www/html/index.html"
          content: "Ansible was here!"

      - name: make httpd accessible through firewall
        firewalld:
          service: "http"
          permanent: true
          immediate: true
          state: enabled

      - name: start the apache service
        service:
          name: "httpd"
          enabled: true
          state: started

      - name: test the service localy
        get_url:
          url: "http://localhost"
          dest: "/tmp/ansible_httpd_test"
          checksum: "sha256:73e373c681304008664ced832f99b10f790411028d369df00023067f844e4a5d"


